#spring:
#  thymeleaf:
#    mode: HTML5
#    encoding: UTF-8
#content-type: text/html
## 开发禁用缓存
#    cache: false
#    datasource:
#      url: jdbc:mysql://localhost:3306/ssmDb?characterEncoding=UTF-8&useSSL=true
#      username: root
#      password: password
#    ## 可省略驱动配置, sprin-boot 会由url检测出驱动类型
#    driver-class-name: com.mysql.jdbc.Driver
#    hikari:application.properties
#    connection-timeout: 60000
#mybatis:
#    mapperLocations: classpath:com/boot/mapper/*.xml
#    typeAliasesPackage: cn.boot.domain
#    # spring-boot默认打印输出info级别以上的，可在此处修改输出级别
#logging:
#    level:
#       root: info

server:
  port: 8080

spring:
  datasource:
      url: jdbc:mysql://119.23.105.170:3306/work?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: work
      password: workworkwork
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: gxun.soft.homework_system.domain
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
     enabled: true